version: '3'
services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - 8080:5173
    restart: unless-stopped
    
    # depends_on:
    #   - postgres_senseinode

  # backend:
  #   image: postgres
  #   env_file: .env
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #   restart: unless-stopped

  # flask:
  #   image: postgres
  #   env_file: .env
  #   environment:
  #     POSTGRES_DB: ${DATABASE_NAME}
  #     POSTGRES_USER: ${DATABASE_USERNAME}
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #   restart: unless-stopped